#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=example_job
#SBATCH --mail-type=BEGIN,END
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=03:00
#SBATCH --account=sadasivan
#SBATCH --partition=devel

# The application(s) to execute along with its input arguments and options:

if [ "$#" -ne 1 ]; then
    echo "Usage: ./run_tests {program}"
    exit 1
fi

export LD_LIBRARY_PATH=$PWD/libwb/build/:$LD_LIBRARY_PATH

if [ "$#" -eq  1 ]; then
    ./$1 -e test/mm2-fast_lisa_pos.dat -i test/mm2-fast_minimizer.dat -t vector
fi
